apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nabat.fullname" . }}-grafana-datasources
  namespace: {{ .Values.namespace }}
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://{{ include "nabat.fullname" . }}-prometheus:9090
      isDefault: true
    - name: Loki
      type: loki
      access: proxy
      url: http://{{ include "nabat.fullname" . }}-loki:3100
    - name: Zipkin
      type: zipkin
      access: proxy
      url: http://{{ include "nabat.fullname" . }}-zipkin:9411
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nabat.fullname" . }}-grafana
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nabat.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/component: grafana
        {{- include "nabat.labels" . | nindent 8 }}
    spec:
      containers:
      - name: grafana
        image: {{ .Values.monitoring.grafana.image }}
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: {{ .Values.monitoring.grafana.adminPassword }}
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /etc/grafana/provisioning/datasources
          name: datasources
        - mountPath: /var/lib/grafana
          name: storage
      volumes:
      - name: datasources
        configMap:
          name: {{ include "nabat.fullname" . }}-grafana-datasources
      - name: storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nabat.fullname" . }}-grafana
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/component: grafana
  ports:
  - port: 3000
  type: NodePort
