apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nabat.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.global.jwtSecret | quote }}
  postgres-password: {{ .Values.postgres.password | quote }}
