apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nabat.fullname" . }}-voting-postgres-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.votingPostgres.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nabat.fullname" . }}-voting-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nabat.labels" . | nindent 4 }}
    app.kubernetes.io/component: voting-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: voting-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/component: voting-postgres
        {{- include "nabat.labels" . | nindent 8 }}
    spec:
      containers:
      - name: postgres
        image: {{ .Values.votingPostgres.image }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.votingPostgres.database }}
        - name: POSTGRES_USER
          value: {{ .Values.votingPostgres.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.votingPostgres.password }}
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
        startupProbe:
          exec:
            command:
            - pg_isready
            - -U
            - {{ .Values.votingPostgres.user }}
            - -d
            - {{ .Values.votingPostgres.database }}
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 30
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - {{ .Values.votingPostgres.user }}
            - -d
            - {{ .Values.votingPostgres.database }}
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: {{ include "nabat.fullname" . }}-voting-postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nabat.fullname" . }}-voting-postgres
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/component: voting-postgres
  ports:
  - port: 5432
